-- Q.1 What is total revenue generated by male vs Female customers?
select gender, sum(purchase_amount) as revenue
from customer
group by gender;

-- Q.2 Which customer's used a discount but still spent more than average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer);

-- Q.3 Which are the top 5 products with the highest average review rating.
select item_purchased, round(avg(review_rating),2) as "avg_rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q.4 Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type, round(avg(purchase_amount),2) as "Average_amount"
from customer
where shipping_type in ("Express", "Standard")
group by shipping_type;


select subscription_status, round(avg(purchase_amount),2) as "Average_amount"
from customer
where subscription_status in ("Yes", "No")
group by subscription_status;

-- Q.5 Do Subscribed Customer Spend More? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
count(customer_id) as total_customers,
round(sum(purchase_amount),2) as total_revenue,
round(avg(purchase_amount),2) as avg_spend
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

-- Q.6 Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
round(100* sum(case when discount_applied = "Yes" then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- Q.7 Segment customers intp New, Returning and loyal based on their total number of previous purchases
with customer_type as (
select customer_id, previous_purchases,
case 
	when previous_purchases = 1 then "New"
    when previous_purchases between 1 and 10 then "Regular"
    else "Loyal"
    end as customer_segment
from customer
)

select customer_segment, count(*) as "Number_of_Customers"
from customer_type
group by customer_segment;


-- Q.8 What are top 3 most purchased products within each category?
with items_count as (
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)


select item_rank, category, item_purchased, total_orders
from items_count
where item_rank < 4;

-- Q.9 Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as Repeat_Buyers
from customer
where previous_purchases > 5
group by subscription_status;

-- Q.10 What is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as revenue
from customer
group by age_group
order by revenue desc;
